STATUS_VALIDATION_FAILED = "validation_failed"

DEFAULT_TUBE_RACK_SIZE = 96

# SS entities
STUDY_HERON = "Heron Project"
STUDY_ENTITY = "studies"
PLATE_PURPOSE_ENTITY = "purposes"
EXTRACT_PLATE_PURPOSE = "LHR Stock"
EXTRACT_TR_PURPOSE_96 = "TR Stock 96"
LYSATE_PLATE_PURPOSE = "Heron Lysed Plate"
LYSATE_TR_PURPOSE = "Heron Lysed Tube Rack"
